name: NPM Publish

on:
  workflow_dispatch: # 支持手动触发

permissions:
  contents: write # 允许写入代码库内容
  packages: write # 允许写入包
  id-token: write # 允许写入 ID 令牌

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Publish to NPM
        run: |
          # 洁癖把 只喜欢双数版本号
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          ls -a ~
          cat ~/.npmrc
          npm version patch
          npm version patch
          VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          npm login
          npm publish --access public --no-git-tag-version --token ${{ secrets.NPM_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag and commit version update
        run: |
          git add .
          git commit -m "chore: update version to ${{ env.PACKAGE_VERSION }}"
          git tag "v${{ env.PACKAGE_VERSION }}"
          git push
          git push origin "v${{ env.PACKAGE_VERSION }}"

      - name: Read the latest changelog section
        id: changelog
        run: |
          # 读取 CHANGELOG.md 中最新版本的 changelog
          changelog=$(awk '/^## \[/ {f=1} f && /^###/ {print $0} /^## \[/ {f=0}' CHANGELOG.md)
          echo "::set-output name=changelog::$changelog"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/
          release_notes: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
